# Generated by Django 4.2.7 on 2023-11-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=1, upload_to='book_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, to='core.genre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='genre',
            field=models.ManyToManyField(blank=True, to='core.genre'),
        ),
    ]
