# Generated by Django 4.2.7 on 2023-11-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='genre',
            field=models.ManyToManyField(null=True, to='core.genre'),
        ),
    ]
