# Generated by Django 4.2.7 on 2024-03-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/user.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
