# Generated by Django 4.2.7 on 2024-03-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
