# Generated by Django 4.2.7 on 2024-03-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_traderequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderequest',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected'), ('I', 'Invalid')], default='P', max_length=1),
        ),
    ]
