# Generated by Django 4.2.7 on 2024-03-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_traderequest_seen_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderequest',
            name='request_date',
            field=models.DateTimeField(),
        ),
    ]
