# Generated by Django 4.2.7 on 2024-03-30 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_traderequest_request_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='traderequest',
            unique_together=set(),
        ),
    ]
