# Generated by Django 4.2.7 on 2024-03-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_book_genre_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Invalid', 'Invalid')], default='Pending', max_length=10),
        ),
    ]
