# Generated by Django 4.2.7 on 2024-04-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_book_user_alter_report_reported_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
