# Generated by Django 4.2.7 on 2024-04-07 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_trademeet_receiver_remove_trademeet_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='trademeet',
            name='receiver',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='trademeet_receiver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trademeet',
            name='sender',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='trademeet_sender', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
