# Generated by Django 4.2.7 on 2024-04-12 00:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_trademeet_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Invalid', 'Invalid'), ('Deleted', 'Deleted')], default='Pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='TradeMeet',
        ),
        migrations.AddField(
            model_name='rating',
            name='TradeRequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_request', to='core.traderequest'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
