# Generated by Django 4.2.7 on 2024-04-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_rating_alter_traderequest_status_delete_trademeet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('SPAM', 'Spam'), ('INAPPROPRIATE CONTENT', 'Inappropriate Content'), ('DIDNOT APPEAR', 'Didnot Appear'), ('FAKE BOOK', 'Fake Book')], max_length=50),
        ),
    ]
