# Generated by Django 4.2.7 on 2024-04-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('SP', 'Spam'), ('IC', 'Inappropriate Content'), ('DA', 'Didnot Appear'), ('FB', 'Fake Book')], max_length=50),
        ),
    ]
