# Generated by Django 4.2.7 on 2024-04-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_trademeet_is_accepted_trademeet_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trademeet',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='suspended_date',
            field=models.DateField(null=True),
        ),
    ]
