# Generated by Django 4.2.7 on 2024-04-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_trademeet_status_user_is_suspended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('SP', 'Spam'), ('IC', 'Inappropriate Content'), ('DA', 'Didnot Appear'), ('FB', 'Fake Book'), ('WM', 'Wrong Trade Meet Place')], max_length=50),
        ),
    ]
