# Generated by Django 4.2.7 on 2024-04-14 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_report_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='traderequest',
        ),
        migrations.AddField(
            model_name='rating',
            name='rater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rater', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
