# Generated by Django 4.2.7 on 2024-04-15 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_rating_traderequest_rating_rater'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('rater', 'user')},
        ),
    ]
