# Generated by Django 4.2.7 on 2024-04-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suspend_count',
            field=models.IntegerField(default=0),
        ),
    ]
