# Generated by Django 4.2.7 on 2024-04-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_trademeet_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademeet',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
