# Generated by Django 4.2.7 on 2024-04-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='suspended_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
