# Generated by Django 4.2.7 on 2024-04-01 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_traderequest_status'),
        ('chat', '0002_remove_message_user_message_receiver_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='trade_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='core.traderequest'),
        ),
    ]
