# Generated by Django 4.2.7 on 2024-04-06 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
